version: '3'
services:
  web:
    build: ./web
    ports:
      - "5050:5050"
    links:
      - db
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
  
  db:
    build: ./db

  datadog-agent:
    image: datadog/agent:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc/:/host/proc/:ro"
      - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"
    environment:
      - DD_API_KEY=XXX
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true